runtime: python
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "3.12"
env: flex
entrypoint: uvicorn main:app --host 0.0.0.0 --port=8080

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 20

handlers:
  - url: /.*
    script: auto
    secure: always
