import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

MONGO_URI = os.getenv("MONGO_URI")
DB_NAME = os.getenv("DB_NAME")
USERINFO_COLLECTION = os.getenv("USERINFO_COLLECTION")
MEDICAL_COLLECTION = os.getenv("MEDICATION_COLLECTION")
GOOGLE_CALENDAR_COLLECTION = os.getenv("GOOGLE_CALENDAR_COLLECTION")
GMAIL_COLLECTION = os.getenv("GMAIL_COLLECTION")  
PATIENT_KEY_COLLECTION = os.getenv("PATIENT_KEY_COLLECTION")
PATIENT_DATA_COLLECTION = os.getenv("PATIENT_DATA_COLLECTION")

SECRET_KEY = os.getenv("SECRET_KEY")
CHAT_GPT_API_KEY = os.getenv("CHAT_GPT_API_KEY")
GOOGLE_CLIENT_ID= os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET= os.getenv("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI")
GOOGLE_GMAIL_REDIRECT_URI = os.getenv("GOOGLE_GMAIL_REDIRECT_URI")

